### ISSUE TITLE
Add Support for Retrieving All Album Data

### ISSUE THREAD

**Issue by DavidBerdik** [Duq-CPMA-536-Spring-2024/Duq-CPMA-536-Spring-2024#1]
As an Alexa device, I want to retrieve a complete list of the albums and the contents of each album on the server.

Definition of Done: A new endpoint is added to the server that, when accessed, returns a JSON list of all albums and the contents of each album.

**Comment by Allemr** [comment]
10 hours - Learning Flask/waittress/json + researching relevant modules
1 hour - Planning pseudocode/edge cases
4 hours - Coding

**Comment by Allemr** [comment]
2 hours - Considering/testing improvements to issue1
1 hour - Considering/testing how issue2 will interact with issue1

**Comment by Allemr** [comment]
3 hours - assisting Claire with issue2 + dealing with Merge conflict 
1 hour - initial considerations on combining functionality with Claire's function

**Comment by DavidBerdik** [comment]
> 3 hours - assisting Claire with issue2 + dealing with Merge conflict
> 1 hour - initial considerations on combining functionality with Claire's function

This is in reference to #12, right?
