### ISSUE TITLE
Refactor Album Listing

### ISSUE THREAD

**Issue by DavidBerdik** [Duq-CPMA-536-Spring-2024/Duq-CPMA-536-Spring-2024#12]
@Allemr's work on #1 and @claireheimburg's work on #2 has overlap. The code should be refactored to allow for reuse of code between these two tasks as appropriate.

Definition of Done: The work in #1 is adapted to use #2 as a dependency.

**Comment by claireheimburg** [comment]
2 hours - creating new function 
2 hours - getting function to work within issue1 and issue2 code

**Comment by Allemr** [comment]
1 hour - figuring out how to have issue1 be dependent on issue2
1 hour - coding some function calling within issue1/function improvements on the two issues
1 hour - researching/coding some helper functionality to work with issue1 and issue2
