### ISSUE TITLE
Remove Server Home Page

### ISSUE THREAD

**Issue by DavidBerdik** [Duq-CPMA-536-Spring-2024/Duq-CPMA-536-Spring-2024#16]
The server home page function has no purpose and was only added for the early stages of the project to serve as an example of creating an endpoint using Flask. It should be removed.

Definition of Done: `server_home_page()` is completely removed from the code.

**Comment by Niteeesh** [comment]
Nothing interesting home page is removed. Let me know if i can add a home page with something interesting
