### ISSUE TITLE
Add Support for Retrieving Data for Specific Album

### ISSUE THREAD

**Issue by DavidBerdik** [Duq-CPMA-536-Spring-2024/Duq-CPMA-536-Spring-2024#2]
As an Alexa device, I want to retrieve the contents of a specific album on the server.

Definition of Done: A new endpoint is added to the server that, when accessed, returns a JSON list containing the contents of a specific album.

**Comment by claireheimburg** [comment]
3 hours - Learning flask/waitress/json
1 hour - Researching how issue1 code works
1 hour - Manipulating code from issue1
3 hours - Coding issue2
