### ISSUE TITLE
Add Support for Playback of a Song in an Album

### ISSUE THREAD

**Issue by DavidBerdik** [Duq-CPMA-536-Spring-2024/Duq-CPMA-536-Spring-2024#3]
As an Alexa device, I want to play back a song inside an album.

Definition of Done: A new endpoint is added that, when accessed, will play back the given song contained with the given album. The endpoint that is created should specify the name of the album as well as the name of the file within the album to play.

**Comment by csclass24** [comment]
Watched online videos and reviewed codes with similar functionality on GitHub and other sources. Started indexing the albums and the songs/audio files within the folders saved on my local drive. Future: Simplify the code an minimize redundancy by referencing directory for songs, once per album. It takes probably half the allocated time.
